### ISSUE TITLE
Shortcut key doesn't match keyboard layout

### ISSUE THREAD

**Issue by metawops** [deseven/icanhazshortcut#49]
I'm using a keyboard with an ISO-DE layout.
When I click on the Shortcut combination control to set a shortcut keystroke for an Action I get totally different results than keys I pressed. Obviously, ichs uses some kind of "hard wired" US/ANSI keyboard layout here.

**Comment by deseven** [comment]
Global hotkeys in macOS are layout-neutral and don't follow language-specific keyboards in any way.
See https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h#L198

In order to make it work i will have to handle it manually, load currently activated layouts and create bindings to original ANSI keys. Which is again may not be optimal for all people (for example i have a keyboard with russian layout, but i don't want to see my shortcuts tied to russian keys, it will be pretty confusing).

Overall i don't think it's worth the trouble, sorry. However, i'll leave it open to see if there's any real interest from other people, just in case.
