### ISSUE TITLE
Character Encoding issue

### ISSUE THREAD

**Issue by cvickery** [deseven/icanhazshortcut#56]
If the text involved is not ASCII, it seems to get mangled.

For example if the shortcut is `echo “iCanHazShortcut” | pbcopy` then pasting gives ‚ÄúiCanHazShortcut‚Äù because the UTF-8 curly quotes at the beginning and end of the echo string are treated, erroneously, as ASCII.

If the shortcut is typed into the shell, it works correctly, and preceding the shortcut definition with LANG=en_US.UTF-8 in iCanHasShortcut setup seems to make no difference.

**Comment by deseven** [comment]
Pipes create subshells, so if you want to set `LANG` explicitly it should be done in both shells you spawn:
`LANG=en_US.UTF-8 echo “iCanHazShortcut” | LANG=en_US.UTF-8 pbcopy`

But first declaration can be omitted because `echo` actually doesn't care about encodings:
`echo “iCanHazShortcut” | LANG=en_US.UTF-8 pbcopy`

However, I recommend setting your locale variables through your shell config file (`.bash_profile` or similar), add this:
```bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

After that all commands you input in iCHS will use the desired locale parameters.

**Comment by cvickery** [comment]
Ha! I had checked my environment for LANG, but I hadn’t thought to check LC_ALL. Adding that to my .bashrc fixed the problem. Thanks!!
Chris

On Feb 28, 2023, at 11:20 AM, Ivan Novokhatski ***@***.***> wrote:

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***



Pipes create subshells, so if you want to set LANG explicitly it should be done in both shells you spawn:
LANG=en_US.UTF-8 echo “iCanHazShortcut” | LANG=en_US.UTF-8 pbcopy

But first declaration can be omitted because echo actually doesn't care about encodings:
echo “iCanHazShortcut” | LANG=en_US.UTF-8 pbcopy

However, I recommend setting your locale variables through your shell config file (.bash_profile or similar), add this:

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

**Comment by deseven** [comment]
I usually just call `locale` that quickly shows all related variables.
You're welcome! Closing this.
